name: Playwright NUnit Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Use appropriate .NET version

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Run NUnit tests
      run: dotnet test --filter PlaywrightTests

    - name: Install Allure Command Line Interface (CLI)
      run: |
        wget -qO - https://dl.bintray.com/qameta/generic/allure-cli-2.13.8-linux.tar.gz | tar -xz
        sudo mv allure-2.13.8 /usr/local/bin/allure

    - name: Generate Allure Report
      run: allure generate allure-results --clean

    - name: Upload Allure Results as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    - name: Open Allure Report (Optional)
      run: allure open allure-results
