name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Updated to the latest stable version
    - name: Setup .NET
      uses: actions/setup-dotnet@v3  # Updated to the latest stable version
      with:
        dotnet-version: '9.0.x'
    - name: Restore Dependencies
      run: dotnet restore  # Ensure dependencies are restored
    - name: Build Application
      run: dotnet build
    - name: Ensure Browsers are Installed
      run: npx playwright install --with-deps
    - name: Run Your Tests
      run: dotnet test


