name: Playwright NUnit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    # ✅ Install Playwright and Browsers
    - name: Install Playwright and Browsers
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install --with-deps

    - name: Run Tests with Allure Reporting
      run: dotnet test --logger "trx;LogFileName=allure-results/test-results.trx"

    # ✅ Upload Allure Results as Artifact
    - name: Upload Allure Results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results
        retention-days: 20

    # ✅ Install Allure CLI
    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/latest/download/allure-2.23.0.tgz -O allure.tgz
        tar -zxvf allure.tgz
        sudo mv allure-2.23.0 /usr/local/allure
        echo "export PATH=/usr/local/allure/bin:$PATH" >> $GITHUB_ENV
        allure --version  # Verify installation

    # ✅ Get Allure history from gh-pages branch
    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    # ✅ Generate Allure Report
    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    # ✅ Publish Allure Report to GitHub Pages
    - name: Deploy Allure Report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-report
