name: Playwright NUnit Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Use appropriate .NET version

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Run NUnit tests
      run: dotnet test --filter PlaywrightTests --logger:"nunit;LogFilePath=allure-results/test-results.xml"

    # Install Allure CLI version 3.13.3
    - name: Install Allure Command Line Interface (CLI) version 3.13.3
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/3.13.3/allure-3.13.3.zip -O allure-3.13.3.zip
        unzip allure-3.13.3.zip
        sudo mv allure-3.13.3 /usr/local/bin/allure

    # Generate Allure Report
    - name: Generate Allure Report
      run: allure generate allure-results --clean

    # Upload Allure Results as Artifact
    - name: Upload Allure Results as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results

    # Optionally open the Allure Report (Optional)
    - name: Open Allure Report (Optional)
      run: allure open allure-results
