name: Playwright NUnit Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Use appropriate .NET version

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run NUnit tests
      run: dotnet test --filter PlaywrightTests --logger "trx;LogFileName=allure-results/test-results.trx"

    # ✅ Install Allure CLI properly
    - name: Install Allure CLI
      run: |
        sudo apt update
        sudo apt install -y allure
        allure --version  # Check if Allure is installed

    # ✅ Generate Allure Report
    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    # ✅ Upload Allure Results as Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    # ✅ Open Allure Report (Optional)
    - name: Open Allure Report (Optional)
      run: allure open allure-report
