name: Playwright NUnit Tests

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Use appropriate .NET version

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    # Run NUnit tests and use the TRX logger to generate results
    - name: Run NUnit tests
      run: dotnet test --filter PlaywrightTests --logger "trx;LogFileName=allure-results/test-results.trx"

    # Install Allure Command Line Interface (CLI)
    - name: Install Allure Command Line Interface (CLI) version 2.13.8
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.13.8/allure-2.13.8.zip -O allure-2.13.8.zip
        unzip allure-2.13.8.zip
        sudo mv allure-2.13.8 /usr/local/bin/allure

    # Generate Allure Report from the TRX results
    - name: Generate Al
