name: Playwright NUnit Tests

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'  # Use appropriate .NET version

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build

    - name: Run NUnit tests
      run: dotnet test --filter PlaywrightTests
