on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use the latest version of checkout
    - name: Setup .NET
      uses: actions/setup-dotnet@v4  # Use the latest version of setup-dotnet
      with:
        dotnet-version: '9.0.x'
    - name: Restore Dependencies
      run: dotnet restore  # Ensure dependencies are restored
    - name: Build Application
      run: dotnet build
    - name: Ensure Browsers are Installed
      run: npx playwright install --with-deps  # Ensures browsers are available for Playwright
    - name: Run Your Tests
      run: dotnet test
